# Generated by Django 4.0 on 2021-12-30 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0004_alter_gestion_gestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.gestion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Foda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppoa.area')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField()),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('foda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppoa.foda')),
            ],
        ),
        migrations.CreateModel(
            name='Perspectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspectiva', models.CharField(max_length=400)),
                ('objetivo', models.TextField()),
                ('objetivoestrategico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppoa.objetivoestrategico')),
            ],
        ),
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_inicio', models.DateField()),
                ('f_fin', models.DateField()),
                ('iniciativa', models.TextField()),
                ('i_objetivo', models.TextField()),
                ('actividad', models.CharField(choices=[('po', 'Politica'), ('pl', 'PLan'), ('pr', 'Proyecto'), ('pa', 'Programa'), ('a', 'Actividad'), ('t', 'Tarea')], max_length=2)),
                ('r_operativo', models.TextField()),
                ('i_indices', models.TextField()),
                ('resultados', models.TextField()),
                ('condicionantes', models.TextField()),
                ('perspectiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppoa.perspectiva')),
            ],
        ),
    ]
