# Generated by Django 4.0.1 on 2022-01-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_unidad_gestion'),
        ('ppoa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='foda',
            name='area',
        ),
        migrations.CreateModel(
            name='UnidadGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppoa.area')),
                ('unidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='foda',
            name='unidadgestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ppoa.unidadgestion'),
            preserve_default=False,
        ),
    ]
