# Generated by Django 4.0.1 on 2022-01-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_unidad_gestion'),
        ('ppoa', '0002_remove_area_unidad_remove_foda_area_unidadgestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadgestion',
            name='gestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.gestion'),
            preserve_default=False,
        ),
    ]
