# Generated by Django 4.0.1 on 2022-01-16 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_unidad_gestion'),
        ('ppoa', '0003_unidadgestion_gestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foda',
            name='unidadgestion',
        ),
        migrations.RemoveField(
            model_name='objetivoestrategico',
            name='foda',
        ),
        migrations.AddField(
            model_name='foda',
            name='gestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.gestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objetivoestrategico',
            name='unidadgestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ppoa.unidadgestion'),
            preserve_default=False,
        ),
    ]
