# Generated by Django 4.0.1 on 2022-01-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppoa', '0004_remove_foda_unidadgestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foda',
            name='codigo',
            field=models.CharField(choices=[('DA', 'DA'), ('FO', 'FO'), ('DO', 'DO'), ('FA', 'FA')], max_length=10),
        ),
    ]
