# Generated by Django 4.0.1 on 2022-01-22 00:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ppoa', '0007_iniciativa_medio_verificacion_iniciativa_porcentaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_foda', models.CharField(choices=[('DA', 'DA'), ('FO', 'FO'), ('DO', 'DO'), ('FA', 'FA')], max_length=10, verbose_name='Codigo de Foda')),
                ('estrategia', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppoa.area')),
            ],
        ),
        migrations.CreateModel(
            name='IniciativaPDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciativa', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='iniciativa',
            name='perspectiva',
        ),
        migrations.RemoveField(
            model_name='objetivoestrategico',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='objetivoestrategico',
            name='unidadgestion',
        ),
        migrations.RemoveField(
            model_name='unidadgestion',
            name='foda',
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='unidadgestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ppoa.unidadgestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perspectiva',
            name='codigo',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadgestion',
            name='objetivoestrategico',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estrategia', chained_model_field='estrategia', default=1, on_delete=django.db.models.deletion.CASCADE, to='ppoa.objetivoestrategico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadgestion',
            name='perspectiva',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='objetivoestrategico', chained_model_field='objetivoestrategico', default=1, on_delete=django.db.models.deletion.CASCADE, to='ppoa.perspectiva'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='porcentaje',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='0001', message='Solo se permiten numeros del 0 al 100', regex='^([0-9]|[1-9][0-9]|[100]){1}$')]),
        ),
        migrations.AlterField(
            model_name='unidadgestion',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='unidad', chained_model_field='unidad', on_delete=django.db.models.deletion.CASCADE, to='ppoa.area'),
        ),
        migrations.DeleteModel(
            name='Foda',
        ),
        migrations.AddField(
            model_name='iniciativapdi',
            name='perspectiva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppoa.perspectiva'),
        ),
        migrations.AddField(
            model_name='objetivoestrategico',
            name='estrategia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ppoa.estrategia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadgestion',
            name='estrategia',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='area', chained_model_field='area', default=1, on_delete=django.db.models.deletion.CASCADE, to='ppoa.estrategia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadgestion',
            name='iniciativapdi',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='perspectiva', chained_model_field='perspectiva', default=1, on_delete=django.db.models.deletion.CASCADE, to='ppoa.iniciativapdi'),
            preserve_default=False,
        ),
    ]
