# Generated by Django 4.0.1 on 2022-01-23 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppoa', '0010_iniciativa_recurrente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadgestion',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ppoa.area'),
        ),
    ]
