# Generated by Django 4.0.1 on 2022-01-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppoa', '0011_alter_unidadgestion_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciativa',
            name='f_fin',
            field=models.DateField(verbose_name='Fecha de Finalisacion'),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='f_inicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='i_indices',
            field=models.TextField(verbose_name='Indicadores/Indices'),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='r_operativo',
            field=models.TextField(verbose_name='Responsable Operativo'),
        ),
    ]
