# Generated by Django 4.0.6 on 2022-08-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppoa', '0012_alter_iniciativa_f_fin_alter_iniciativa_f_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciativa',
            name='actividad',
            field=models.CharField(choices=[('po', 'Politica'), ('pl', 'Plan'), ('pr', 'Proyecto'), ('pa', 'Programa'), ('a', 'Actividad'), ('t', 'Tarea')], max_length=2),
        ),
    ]
