# Generated by Django 4.0.6 on 2022-08-27 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppoa', '0013_alter_iniciativa_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciativa',
            name='porcentaje',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.RegexValidator(code='0001', message='Solo se permiten numeros del 0 al 100', regex='^([0-9]|[1-9][0-9]|[100]){1}$')]),
        ),
    ]
