# Generated by Django 4.0.6 on 2022-08-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppoa', '0014_alter_iniciativa_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciativa',
            name='presupuesto',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
