# Generated by Django 4.0.6 on 2022-10-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppoa', '0016_iniciativa_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciativa',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Obervaciones y Justificaion'),
        ),
    ]
