# Generated by Django 4.0.6 on 2022-11-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppoa', '0017_alter_iniciativa_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadgestion',
            name='email_unidad',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
