# Generated by Django 4.0.6 on 2022-11-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppoa', '0018_unidadgestion_email_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadgestion',
            name='email_unidad',
        ),
    ]
