# Generated by Django 4.0.6 on 2022-12-09 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppoa', '0019_remove_unidadgestion_email_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciativa',
            name='porcentaje',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.RegexValidator(code='0001', message='Solo se permiten numeros del 0 al 100', regex='^(([0-9]{1})|([1-9][0-9]|100))$')]),
        ),
    ]
