# Generated by Django 4.0.6 on 2023-02-05 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_unidad_email_unidad'),
        ('ppoa', '0020_alter_iniciativa_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadgestion',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppoa.area'),
        ),
        migrations.AlterField(
            model_name='unidadgestion',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.unidad'),
        ),
    ]
