# Generated by Django 3.2.9 on 2021-12-13 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_getion_gestion_gestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.gestion')),
            ],
        ),
    ]
