# Generated by Django 3.2.9 on 2021-12-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='gestion',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
