# Generated by Django 4.0.6 on 2022-11-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_unidad_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='email_unidad',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
