# Generated by Django 3.2.9 on 2021-12-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisos',
            options={'permissions': (('users', 'Permiso al modulo de usuarios'), ('gestion', 'Permiso al Modulo de gestion'))},
        ),
    ]
