# Generated by Django 4.0.1 on 2022-01-13 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_permisos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisos',
            options={'permissions': (('users', 'Permiso al Módulo de Usuarios'), ('gestion', 'Permiso al Módulo de Gestión'), ('ppoa', 'Permiso al Módulo de Plan Operativo Anual'))},
        ),
    ]
