# Generated by Django 4.0.6 on 2022-08-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_permisos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisos',
            options={'permissions': (('users', 'Permiso al modulo de usuarios'), ('gestion', 'Permiso al Modulo de gestion'), ('ppoa', 'Permiso al Modeulo de Planificaion del POA'), ('evaluacion', 'Permiso al Modulo de Evaluacion'))},
        ),
    ]
