# Generated by Django 4.0.6 on 2023-01-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_permisos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisos',
            options={'permissions': (('users', 'Permiso al Módulo de Usuarios'), ('gestion', 'Permiso al Módulo de Gestión'), ('ppoa', 'Permiso al Módulo del Plan Operativo Anual'), ('evaluacion', 'Permiso al Módulo de Evaluación'))},
        ),
    ]
